spring:
  application:
    name: monew_server
    version: 1.0.0
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump,heapdump,users
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persist-authorization: true

  sql:
    init:
      encoding: UTF-8

